---
clone_folder: C:\projects\perl-log-dispatch-filerotate

cache:
  - C:\strawberry
  - C:\cygwin
  - C:\dmake

environment:
  matrix:
    - perl_type: system
    - perl_type: strawberry
    - perl_type: cygwin

install:
  - if not exist "C:\tmp" mkdir C:\tmp
  - 'call .appveyor.cmd perl_setup'
  - '%perl% -V'
  - '%dzil% authordeps --missing | %cpanm% --quiet --notest'
  - '%dzil% listdeps --missing | %cpanm% --verbose'
  - cd C:\projects\perl-log-dispatch-filerotate
  - git config --global user.name "AppVeyor"
  - git config --global user.email "appveyor-not-for-mail@appveyor.com"

build: off

test_script:
  - '%dzil% smoke --release --author'
