---
abstract: 'Log to Files that Archive/Rotate Themselves'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Encode: '0'
  Log::Dispatch: '2.60'
  Log::Dispatch::Screen: '0'
  POSIX: '0'
  Path::Tiny: '0.018'
  Test::More: '0.88'
  Test::Warn: '0'
  perl: '5.008'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Dispatch-FileRotate
provides:
  Log::Dispatch::FileRotate:
    file: lib/Log/Dispatch/FileRotate.pm
    version: '1.37'
  Log::Dispatch::FileRotate::Flock:
    file: lib/Log/Dispatch/FileRotate/Flock.pm
    version: '1.37'
  Log::Dispatch::FileRotate::Mutex:
    file: lib/Log/Dispatch/FileRotate/Mutex.pm
    version: '1.37'
requires:
  Carp: '0'
  Date::Manip: '0'
  Exporter: '0'
  Fcntl: '0'
  File::Spec: '0'
  Log::Dispatch: '2.60'
  Log::Dispatch::File: '0'
  Log::Dispatch::Output: '0'
  base: '0'
  perl: '5.008'
  strict: '0'
  version: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/mschout/perl-log-dispatch-filerotate/issues
  homepage: https://github.com/mschout/perl-log-dispatch-filerotate
  repository: https://github.com/mschout/perl-log-dispatch-filerotate.git
version: '1.37'
x_generated_by_perl: v5.30.3
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
